spring.application.name=gestionreserva


spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.lmjizjmpwpkrnynmlehl&password=StarSTD#3610
spring.datasource.username=postgres.lmjizjmpwpkrnynmlehl
spring.datasource.password=StarSTD#3610
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
